export const keys = [
  {
    code: "Backquote",
    type: "multi-symbols",
    name: { 1: "~", 2: "`", 3: "Ё", 4: null },
  },
  { code: "Digit1", type: "symbols", name: { 1: "!", 2: "1" } },
  {
    code: "Digit2",
    type: "multi-symbols",
    name: { 1: "@", 2: "2", 3: null, 4: '"' },
  },
  {
    code: "Digit3",
    type: "multi-symbols",
    name: { 1: "#", 2: "3", 3: null, 4: "№" },
  },
  {
    code: "Digit4",
    type: "multi-symbols",
    name: { 1: "$", 2: "4", 3: null, 4: ";" },
  },
  { code: "Digit5", type: "symbols", name: { 1: "%", 2: "5" } },
  {
    code: "Digit6",
    type: "multi-symbols",
    name: { 1: "^", 2: "6", 3: null, 4: ":" },
  },
  {
    code: "Digit7",
    type: "multi-symbols",
    name: { 1: "&", 2: "7", 3: null, 4: "?" },
  },
  { code: "Digit8", type: "symbols", name: { 1: "*", 2: "8" } },
  { code: "Digit9", type: "symbols", name: { 1: "(", 2: "9" } },
  { code: "Digit0", type: "symbols", name: { 1: ")", 2: "0" } },
  { code: "Minus", type: "symbols", name: { 1: "_", 2: "-" } },
  { code: "Equal", type: "symbols", name: { 1: "+", 2: "=" } },
  { code: "Backspace", type: "backspace", name: "Backspace" },
  { code: "Tab", type: "tab", name: "Tab" },
  { code: "KeyQ", type: "letters", name: { en: "Q", ru: "Й" } },
  { code: "KeyW", type: "letters", name: { en: "W", ru: "Ц" } },
  { code: "KeyE", type: "letters", name: { en: "E", ru: "У" } },
  { code: "KeyR", type: "letters", name: { en: "R", ru: "К" } },
  { code: "KeyT", type: "letters", name: { en: "T", ru: "Е" } },
  { code: "KeyY", type: "letters", name: { en: "Y", ru: "Н" } },
  { code: "KeyU", type: "letters", name: { en: "U", ru: "Г" } },
  { code: "KeyI", type: "letters", name: { en: "I", ru: "Ш" } },
  { code: "KeyO", type: "letters", name: { en: "O", ru: "Щ" } },
  { code: "KeyP", type: "letters", name: { en: "P", ru: "З" } },

  {
    code: "BracketLeft",
    type: "multi-symbols",
    name: { 1: "{", 2: "[", 3: "Х", 4: null },
  },

  {
    code: "BracketRight",
    type: "multi-symbols",
    name: { 1: "}", 2: "]", 3: "Ъ", 4: null },
  },
  {
    code: "Backslash",
    type: "multi-symbols",
    name: { 1: "|", 2: "\\", 3: "\\", 4: "/" },
  },
  { code: "Delete", type: "del", name: "Del" },
  { code: "CapsLock", type: "caps", name: "CapsLock" },
  { code: "KeyA", type: "letters", name: { en: "A", ru: "Ф" } },
  { code: "KeyS", type: "letters", name: { en: "S", ru: "Ы" } },
  { code: "KeyD", type: "letters", name: { en: "D", ru: "В" } },
  { code: "KeyF", type: "letters", name: { en: "F", ru: "А" } },
  { code: "KeyG", type: "letters", name: { en: "G", ru: "П" } },
  { code: "KeyH", type: "letters", name: { en: "H", ru: "Р" } },
  { code: "KeyJ", type: "letters", name: { en: "J", ru: "О" } },
  { code: "KeyK", type: "letters", name: { en: "K", ru: "Л" } },
  { code: "KeyL", type: "letters", name: { en: "L", ru: "Д" } },

  {
    code: "Semicolon",
    type: "multi-symbols",
    name: { 1: ":", 2: ";", 3: "Ж", 4: null },
  },
  {
    code: "Quote",
    type: "multi-symbols",
    name: { 1: '"', 2: "'", 3: "Э", 4: null },
  },

  { code: "Enter", type: "enter", name: "Enter" },
  { code: "ShiftLeft", type: "shift-left", name: "Shift" },
  { code: "KeyZ", type: "letters", name: { en: "Z", ru: "Я" } },
  { code: "KeyX", type: "letters", name: { en: "X", ru: "Ч" } },
  { code: "KeyC", type: "letters", name: { en: "C", ru: "С" } },
  { code: "KeyV", type: "letters", name: { en: "V", ru: "М" } },
  { code: "KeyB", type: "letters", name: { en: "B", ru: "И" } },
  { code: "KeyN", type: "letters", name: { en: "N", ru: "Т" } },
  { code: "KeyM", type: "letters", name: { en: "M", ru: "Ь" } },
  {
    code: "Comma",
    type: "multi-symbols",
    name: { 1: "<", 2: ",", 3: "Б", 4: null },
  },
  {
    code: "Period",
    type: "multi-symbols",
    name: { 1: ">", 2: ".", 3: "Ю", 4: null },
  },
  {
    code: "Slash",
    type: "multi-symbols",
    name: { 1: "?", 2: "/", 3: ",", 4: "." },
  },
  { code: "ArrowUp", type: "up", name: "" },
  { code: "ShiftRight", type: "shift-right", name: "Shift" },
  { code: "ControlLeft", type: "ctrl-left", name: "Ctrl" },
  { code: "MetaLeft", type: "win", name: "" },
  { code: "AltLeft", type: "alt", name: "Alt" },
  { code: "Space", type: "space", name: "" },
  { code: "AltRight", type: "alt", name: "Alt" },
  { code: "ArrowLeft", type: "left", name: "" },
  { code: "ArrowDown", type: "down", name: "" },
  { code: "ArrowRight", type: "right", name: "" },
  { code: "ControlRight", type: "ctrl-right", name: "Ctrl" },
];
