export const keys = [
  { id: "0", type: "esc", name: "Esc" },
  { id: "1", type: "multi-symbols", name: { 1: "~", 2: "`", 3: "Ё", 4: null } },
  { id: "2", type: "symbols", name: { 1: "!", 2: "1" } },
  { id: "3", type: "multi-symbols", name: { 1: "@", 2: "2", 3: null, 4: '"' } },
  { id: "4", type: "multi-symbols", name: { 1: "#", 2: "3", 3: null, 4: "№" } },
  { id: "5", type: "multi-symbols", name: { 1: "$", 2: "4", 3: null, 4: ";" } },
  { id: "6", type: "symbols", name: { 1: "%", 2: "5" } },
  { id: "7", type: "multi-symbols", name: { 1: "^", 2: "6", 3: null, 4: ":" } },
  { id: "8", type: "multi-symbols", name: { 1: "&", 2: "7", 3: null, 4: "?" } },
  { id: "9", type: "symbols", name: { 1: "*", 2: "8" } },
  { id: "10", type: "symbols", name: { 1: "(", 2: "9" } },
  { id: "11", type: "symbols", name: { 1: ")", 2: "0" } },
  { id: "12", type: "symbols", name: { 1: "_", 2: "-" } },
  { id: "13", type: "symbols", name: { 1: "+", 2: "=" } },
  { id: "14", type: "backspace", name: "Backspace" },
  { id: "15", type: "tab", name: "Tab" },
  { id: "16", type: "letters", name: { en: "Q", ru: "Й" } },
  { id: "17", type: "letters", name: { en: "W", ru: "Ц" } },
  { id: "18", type: "letters", name: { en: "E", ru: "У" } },
  { id: "19", type: "letters", name: { en: "R", ru: "К" } },
  { id: "20", type: "letters", name: { en: "T", ru: "Е" } },
  { id: "21", type: "letters", name: { en: "Y", ru: "Н" } },
  { id: "22", type: "letters", name: { en: "U", ru: "Г" } },
  { id: "23", type: "letters", name: { en: "I", ru: "Ш" } },
  { id: "24", type: "letters", name: { en: "O", ru: "Щ" } },
  { id: "25", type: "letters", name: { en: "P", ru: "З" } },
  {
    id: "26",
    type: "multi-symbols",
    name: { 1: "{", 2: "[", 3: "Х", 4: null },
  },
  {
    id: "27",
    type: "multi-symbols",
    name: { 1: "}", 2: "]", 3: "Ъ", 4: null },
  },
  {
    id: "28",
    type: "multi-symbols",
    name: { 1: "|", 2: "\\", 3: "\\", 4: "/" },
  },
  { id: "29", type: "caps", name: "CapsLock" },
  { id: "30", type: "letters", name: { en: "A", ru: "Ф" } },
  { id: "31", type: "letters", name: { en: "S", ru: "Ы" } },
  { id: "32", type: "letters", name: { en: "D", ru: "В" } },
  { id: "33", type: "letters", name: { en: "F", ru: "А" } },
  { id: "34", type: "letters", name: { en: "G", ru: "П" } },
  { id: "35", type: "letters", name: { en: "H", ru: "Р" } },
  { id: "36", type: "letters", name: { en: "J", ru: "О" } },
  { id: "37", type: "letters", name: { en: "K", ru: "Л" } },
  { id: "38", type: "letters", name: { en: "L", ru: "Д" } },
  {
    id: "39",
    type: "multi-symbols",
    name: { 1: ":", 2: ";", 3: "Ж", 4: null },
  },
  {
    id: "40",
    type: "multi-symbols",
    name: { 1: '"', 2: "'", 3: "Э", 4: null },
  },

  { id: "41", type: "del", name: "Del" },
  { id: "42", type: "enter", name: "Enter" },
  { id: "43", type: "shift-left", name: "Shift" },
  { id: "44", type: "letters", name: { en: "Z", ru: "Я" } },
  { id: "45", type: "letters", name: { en: "X", ru: "Ч" } },
  { id: "46", type: "letters", name: { en: "C", ru: "С" } },
  { id: "47", type: "letters", name: { en: "V", ru: "М" } },
  { id: "48", type: "letters", name: { en: "B", ru: "И" } },
  { id: "49", type: "letters", name: { en: "N", ru: "Т" } },
  { id: "50", type: "letters", name: { en: "M", ru: "Ь" } },
  {
    id: "51",
    type: "multi-symbols",
    name: { 1: "<", 2: ",", 3: "Б", 4: null },
  },
  {
    id: "52",
    type: "multi-symbols",
    name: { 1: ">", 2: ".", 3: "Ю", 4: null },
  },
  {
    id: "53",
    type: "multi-symbols",
    name: { 1: "?", 2: "/", 3: ",", 4: "." },
  },
  { id: "54", type: "up", name: "↑" },
  { id: "55", type: "shift-right", name: "Shift" },
  { id: "56", type: "ctrl-left", name: "Ctrl" },
  { id: "57", type: "win", name: "" },
  { id: "58", type: "alt", name: "Alt" },
  { id: "59", type: "space", name: "" },
  { id: "60", type: "alt", name: "Alt" },
  { id: "61", type: "ctrl-right", name: "Ctrl" },
  { id: "62", type: "left", name: "←" },
  { id: "63", type: "down", name: "↓" },
  { id: "64", type: "right", name: "→" },
  { id: "65", type: "fn", name: "Fn" },
];
